// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { API_CONFIG, validateConfig } from '@/config/api';

// Validate configuration on import
validateConfig();

const SUPABASE_URL = API_CONFIG.supabase.url;
const SUPABASE_PUBLISHABLE_KEY = API_CONFIG.supabase.key;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});